name: File checker

on: push

jobs:
  check_files:
    runs-on: ubuntu-latest
    outputs:
      # Output variable to store the list of missing files
      missing_files: ${{ steps.set_output.outputs.missing_files }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up variables
        id: set_output
        run: echo "::set-output name=missing_files::"

      - name: Check Files
        id: check_files
        run: |
          missing_files=""
          for file in LICENSE README.md requirements.txt NOTICE setup.py; do
            echo "Checking $file"
            if [ ! -f "$file" ]; then
              echo "::error::File $file does not exist!"
              missing_files="$missing_files $file"
            fi
          done

      - name: Output missing files
        if: steps.check_files.run.outputs.missing_files != ''
        run: |
          echo "::set-output name=missing_files::$missing_files"
          exit 1
          
      - name: All Files Exist
        if: steps.check_files.run.outputs.missing_files == ''
        run: echo All files exist! No missing files.
