name: File checker

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Check mandatory files
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "LICENSE, README.md, requirements.txt, NOTICE, setup.py"
          fail: true
        
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!

