name: Check Files

on: [push, pull_request]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check files
        run: |
          # Define the list of filenames you want to check
          FILES_TO_CHECK=("LICENSE" "README.md" "requirements.txt" "NOTICE" "setup.py")

          # Initialize a variable to track missing files
          MISSING_FILES=()

          # Check if each file exists in the root directory
          for FILE in "${FILES_TO_CHECK[@]}"; do
            if [ ! -f "$FILE" ]; then
              MISSING_FILES+=("$FILE")
            fi
          done

          # Output the missing files
          if [ ${#MISSING_FILES[@]} -eq 0 ]; then
            echo "All files exist."
          else
            echo "The following files are missing:"
            for MISSING_FILE in "${MISSING_FILES[@]}"; do
              echo "- $MISSING_FILE"
            done
            echo "::error::One or more files are missing."
            exit 1
          fi
